### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Comment by mertyildiran** [comment]
@ralic Do you want to contribute to my other projects like [Dragonfire](https://github.com/mertyildiran/Dragonfire), [Dragonfire-RaspberryPi](https://github.com/mertyildiran/Dragonfire-RaspberryPi), [Dermatron](https://github.com/mertyildiran/Dermatron) or [telve.net](https://github.com/DragonComputer/telve.net)? I actually discontinued Cerebrum because of the technological challenges. With today's technology it's impossible. Either machine learning algorithms are inadequate or computer hardware insufficient, maybe both.

**Comment by mertyildiran** [comment]
@ralic I'm also willing to make academic publications through these projects. Maybe we can work together?

**Comment by ralic** [comment]
Hi Mertyildrian,

Sure, if I can do some help, I am still doing the installing and try to understand further about this work. I may also help update the other projects you had mentioned.

Best,
Ralic

**Comment by mertyildiran** [comment]
@ralic Great! We can discuss and implement new features or fix some issues together. Also maybe I can contribute to your projects too. Please tell me if there is a project of yours needs support.

**Comment by mertyildiran** [comment]
@ralic Also I have invited you to this organization [Dragon Computer](https://github.com/DragonComputer) please join us.

**Comment by mertyildiran** [comment]
@ralic please take a look to this chat room time to time: https://gitter.im/DragonComputer/Lobby

**Pull request merged**
